### ISSUE TITLE
Nested fields in the Random API

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#117]
Just following up on some discussion at https://github.com/google/boardgame.io/pull/116.

Currently, the Random API only allows retrieving random results into fields at the top level of `G`. We should support deeper levels using a syntax like:

```
G = Random.Number(G, 'a.b.c');
G = Random.Shuffle(G, 'players.0.hand');
```

@Stefan-Hanke has some example code in https://github.com/google/boardgame.io/pull/116 that might serve as a good starting point.

**Comment by Stefan-Hanke** [comment]
I'm on this.

**Comment by Stefan-Hanke** [comment]
I think having all functions in one file is getting unwieldy. However I won't create a second one since my first tackle has been reverted.

The one thing missing now is accessing arrays using `[]` syntax. Anything else that we are missing for expression evaluation?

**Comment by nicolodavis** [comment]
Oh, the only reason I merged the two files into one was because I was wrestling with Rollup and wanted to simplify the dependencies. I don't have any objections to splitting the code as long as the other file is named random.something.js (i.e. someone wanting to dive in will not struggle finding where everything is).

Is the `[]` just a nice to have or actually necessary? I'm guessing we can still do `a.0` and `a.1`, correct?

**Comment by nicolodavis** [comment]
Also, I just came across https://github.com/debitoor/dot-prop-immutable. Not sure if it makes sense to use it directly. Just wanted to bring it to your attention in case it makes our implementation cleaner.

**Comment by Stefan-Hanke** [comment]
This library looks good, and well - it's a drop-in replacement for `deep_get` and `deep_set` which have the very same signatures. The only thing that I would object to that it is yet another dependency. If you're ok with having that dependency, I'd use it.

**Comment by nicolodavis** [comment]
Obsoleted by #119
