### ISSUE TITLE
0.18 release bug

### ISSUE THREAD

**Issue by MOZGIII** [google/boardgame.io#126]
Hi guys.

Release 0.18 does not include file `dist/react.js` in the npm package. Can you please fix it?

For proof look here: https://registry.npmjs.org/boardgame.io/-/boardgame.io-0.18.0.tgz

UPD: seems like you forgot to add it in the `rollup.npm.js`

**Comment by nicolodavis** [comment]
Thanks for bringing this to my attention. Fixed.
