### ISSUE TITLE
`lru-native` fails to compile on Win7

### ISSUE THREAD

**Issue by Stefan-Hanke** [google/boardgame.io#129]
The last commit added - besides the mongo stuff - `lru-native`. This fails to compile since `sys/time.h` cannot be found (see [LRUCache.cc](https://github.com/adzerk/node-lru-native/blob/master/src/LRUCache.cc)).

Has anybody observed the same issue? I should have installed the necessary prerequisites. If you need to know specifics, just ask. (Well, maybe I could try installing cygwin, looks like windows-build-tools only installed a mingw environment)

As a sidenote, that dependency's repository has not seen a commit in two years, and other people have similar issues with it (see e.g. that [one pull request](https://github.com/adzerk/node-lru-native/pull/10) open for a year).

**Comment by nicolodavis** [comment]
Ah, then I'll switch to a different cache implementation.

**Comment by nicolodavis** [comment]
Replaced with `lru-cache`. Let me know if there are any concerns with using this package instead.
