### ISSUE TITLE
Docs for events 

### ISSUE THREAD

**Issue by jstacoder** [google/boardgame.io#137]
After reading through the docs I found I didn’t know enough about `events` to successfully use the framework, and I needed to read the source to really grasp how to utilize them, I think I’ll write a specific section of the docs about events to help others that have that problem

**Comment by nicolodavis** [comment]
Sounds good. There is an [example](https://github.com/google/boardgame.io/blob/master/examples/modules/phases/components/diagram.js) in the examples section of the repo that I originally intended as an interactive way to explain events. Perhaps you can embed that in the page you are writing as well.

**Comment by nicolodavis** [comment]
Also, take note of #141 and #142, which are going to change the API.

**Comment by jstacoder** [comment]
#159

**Comment by nicolodavis** [comment]
This is now done. Feel free to leave feedback about the docs here.
