### ISSUE TITLE
State Id updated on illegal moves

### ISSUE THREAD

**Issue by Stefan-Hanke** [google/boardgame.io#147]
During tests for #145, I've noticed that [these tests](https://github.com/google/boardgame.io/blob/master/src/core/reducer.test.js#L28) check that each dispatched move increments the `_stateID`. The tests are left untouched in that PR, however following line is left to keep them from breaking (in function `canMakeMoveDefault`):
> if (playerID === undefined) return true;

Do we want to update the state ID on moves where `canMakeMove` should return false?

**Comment by nicolodavis** [comment]
Ah, yes, I think we should not update the state ID for invalid moves (the framework should pretend they never happened).

Eventually, we should also extend this to not just invalid *types* of moves, but also invalid combinations of args. For example, the current tic-tac-toe implementation will update the state ID (and turn I believe) even if someone calls it with a cell that's already filled (the user-provided logic still takes care of not updating `G`). We should probably adopt the following semantics to allow users to indicate that a given arg combination is invalid:

- Return the new value of `G` if the move was valid.
- Return nothing if the move was not.

The wrapping reducer will take care of returning the unchanged state.

**Comment by Stefan-Hanke** [comment]
I'm not sure I understand. Currently, #145 already allows a game developer to provide a custom `canMakeMove`, that is called together with all other validations (as part of handling a move inside the reducer). If that method returns `false` the move will not be performed.

E.g., for the TicTacToe-example, we'd have to provide a custom `canMakeMove` as part of its `flow` object that could perform that check.

**Comment by nicolodavis** [comment]
Ah, that works too. I'd originally thought we'd use `canMakeMove` to just disallow:
- moves from out-of-turn players
- moves disallowed in the current phase

I'm not opposed to even supporting both. It's nice to have the logic that determines whether a move is invalid in the move itself (some of the computation that's involved might even be redundant with that required to actually execute the move). Also, unless we provide some syntactic sugar to make `canMakeMove` easier to write, it might end up becoming a long list of unrelated move invalidations that become a maintenance burden:

### Approach 1

```
moveA: (G, ctx) => {
  if (moveAInvalid) return;
  ...
  return { ...G, ... };
}
moveB: (G, ctx) => {
  if (moveAInvalid) return;
  ...
  return { ...G, ... };
}
```

### Approach 2

```
moveA: (G, ctx) => {...}
moveB: (G, ctx) => {...}
canMakeMove(G, ctx, move) {
  if (move == moveA && moveAInvalid) return false;
  if (move == moveB && moveBInvalid) return false;
  return true;
}
```

**Comment by Stefan-Hanke** [comment]
Oh well, I've thought along the _move-is-not-even-defined-by-the-game_ line. E.g. the test I linked in the first post runs an _unknown_ move, that is actually unknown to the game.

Since we already support Approach 2, I'm going to make Approach 1 work.
