### ISSUE TITLE
Disable a move

### ISSUE THREAD

**Issue by rzulian** [google/boardgame.io#161]
How do we want to manage the following scenario?
You are the activePlayer. Your available moves are moveA, moveB and moveC. You pick to do moveA, but we realise that you don't have the available resources (e.g. money, VPs)  to do it. Can we rollback the move?

**Comment by nicolodavis** [comment]
moveA can return undefined in this case.

**Comment by nicolodavis** [comment]
Please ask on the Gitter channel if you need further assistance.
