### ISSUE TITLE
Conditional availableMoves

### ISSUE THREAD

**Issue by jstacoder** [google/boardgame.io#163]
I think it would be nice if we had a callback we could provide in game config, maybe overridable via phase config, that would take state as an argument, and return the array of availableMoves, that way it would be easy to base that on certain values in G, I’ll submit a pull soon, any ideas?

**Comment by jstacoder** [comment]
Oh or better yet, let availableMoves be given as a function, and when it’s a function call it to provide the value, that way when an array is given a default function like `()=>availableMoves` could be used by default

**Comment by nicolodavis** [comment]
Great idea! I like being able to support providing either an array or a function. Let's also make this available both in the global config as well as on a per-phase basis.

**Comment by jstacoder** [comment]
Cool, I’m working up a pull request now.

**Comment by jstacoder** [comment]
I think it would be useful for cases like #161
