### ISSUE TITLE
processMove calling endPhase twice

### ISSUE THREAD

**Issue by janosimas** [google/boardgame.io#175]
I have a situation where I end the turn and the phase at the same time, the new phase has it's own conditions of endTurnIf and endPhaseIf.

- The `processMove` set's the variable `conf` end then activates the `endTurnEvent`. [phase `0`]
- The `endTurnEvent` activates the `endPhaseEvent`. [phase `1`]
- The `processMove` activates the `endPhaseEvent` of the `conf` variable set in the begining. [phase `0`]

This way when the `endPhaseIf` at the end of the `processMove` is called, it calls the phase `0` during the phase `1`.

**Comment by nicolodavis** [comment]
I didn't quite follow that. Do you have time to express this as a failing unit test in this repo? That would make it much easier to follow and debug (if there is a bug).

Were you expecting `endPhaseIf` to not kick in for the new phase?

**Comment by janosimas** [comment]
I did create a test but I can't push because it's not passing the tests! :-p
How can I bypass the test check?

I'm having another error:
```
FAIL src\core\game.test.js

  ● Test suite failed to run

    jest: failed to cache transform results in: 
...
```

Do you know what can it be?

**Comment by jstacoder** [comment]
You should be able to get the test committed by making it expect to fail, instead of it failing an expected success

**Comment by janosimas** [comment]
@jstacoder the test should succeed, but the current state of the framework makes it fail.

**Comment by nicolodavis** [comment]
I think you can also do

`git commit --no-verify`

to commit with failing tests.

**Comment by janosimas** [comment]
I did the pull request #176

**Comment by nicolodavis** [comment]
OK the bug seems clear to me now. Thanks for creating the test! That really helped.

Will work on a fix.

**Comment by nicolodavis** [comment]
Maybe I'll just fix it in your PR (so we can also see the test pass) and merge it in.
