### ISSUE TITLE
Cannot toggle Debug pane on example multiplayer games

### ISSUE THREAD

**Issue by Stefan-Hanke** [google/boardgame.io#178]
When running the examples with `npm run examples`, using <kbd>d</kbd> should toggle the Debug Pane. This works for the singleplayer games, but not for multiplayer ones.

Is this by intention?

**Comment by nicolodavis** [comment]
Do they have debug: false in the config? This is working as intended.

**Comment by Stefan-Hanke** [comment]
Oh my, thanks for the pointer. Opens up the question on why this is done...

**Comment by nicolodavis** [comment]
That's because having multiple overlapping debug panes (one for each player) can be potentially confusing.
