### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by amerine** [google/boardgame.io#18]
Hello! I'm the current registrant of the boardgame.io domain. I had grand plans of doing something vaguely similar to this a couple years ago, but it went the way most ideas do... 🚮

The domain is yours, if you want.

--mark

**Comment by nicolodavis** [comment]
Thank you so much for offering :) How do we transfer it?

**Comment by amerine** [comment]
The absolute easiest way for me would be to transfer it to another dnsimple account. Anything else is/would be a normal domain transfer. If you'd like to do a normal transfer I can unlock it and get authorization code in the hands of someone via a secure medium. 

Let me know what you/the project would like to do.

**Comment by nicolodavis** [comment]
Let's do a normal domain transfer. You can send me details at nicolodavis@gmail.com.

Thanks again, Mark!

**Comment by w74** [comment]
@amerine that's super cool of you to do that!

**Comment by amerine** [comment]
I emailed the authorization code to Nicolo this morning. 

Enjoy the domain, boardgame.io team
