### ISSUE TITLE
Turn goes twice when phase is end

### ISSUE THREAD

**Issue by qsona** [google/boardgame.io#193]
Hi, I'm facing a problem. I set `endTurnIf` hook to always return true. When phase is end, it seems that the turn automatically goes twice.

- `ctx.turn` is added by 2
- `ctx.currentPlayer` goes twice 

I've not dug deeply yet, but I found that the `endTurn` event is dispatched in `function endPhaseEvent` and `endPhase` event is dispatched in `function endTurnEvent` in `src/core/flow.js` . I feel the former should be removed. What do you think?

## Reproduce steps

Here's minimum code for reproducing. Prepares a project as tutorials, then rewrites `src/App.js` as follows:

```js
import { Client } from 'boardgame.io/react';
import { Game, TurnOrder } from 'boardgame.io/core';

const Foo = Game({
  setup: () => {
    return {
      players: {
        '0': { },
        '1': { },
      },
    };
  },

  moves: {
    skip: (G) => G,
  },
  flow: {
    turnOrder: TurnOrder.DEFAULT,
    endTurnIf: () => true,
    phases: [
      {
        name: 'a',
        allowedMoves: ['skip'],
        endPhaseIf: (G, ctx) => ctx.turn === 2,
      },
      {
        name: 'b',
      },
    ],
  }
});

const App = Client({
  game: Foo,
});

export default App;
```

then run `npm start`, and open the web cli (localhost:3000).

then, 

- initial state => turn is 0. currentPlayer is 0.
- do `skip()` => turn is 1. currentPlayer is 1.
- do `skip()` => turn is 3 (expected to 2). currentPlayer is 1 (expected to 0).

**Comment by francoijs** [comment]
It seems like this change of behavior was introduced between versions 0.21.3 and 0.21.4. 
Before version 0.21.4, we had to manually _endPhase_ at the end of a turn, so that the next turn (of next player) begins at the proper phase.

**Comment by nicolodavis** [comment]
Fixed now. Thanks again for the report!

**Comment by theredwillow** [comment]
This appears to still be a problem for me in version ^0.36.0. It doesn't matter if I call it by event or by `endIf` inside the phase definition.

**Comment by nicolodavis** [comment]
Have you considered using TurnOrder.ONCE: https://boardgame.io/documentation/#/turn-order

Does that solve your use case?
