### ISSUE TITLE
allowedMoves is set incorrectly if phase is ended as the result of a move

### ISSUE THREAD

**Issue by drsirmrpresidentfathercharles** [google/boardgame.io#211]
At [this line](https://github.com/google/boardgame.io/blob/8db26d292113944b3c5446c6a50d2f0e4d0077da/src/core/flow.js#L544) in flow, if the phase ends during the move, although the phase is updated in the state, the allowedMoves property is set [here](https://github.com/google/boardgame.io/blob/8db26d292113944b3c5446c6a50d2f0e4d0077da/src/core/flow.js#L563) based on the previous phase because the `conf` variable is not updated with the new phase configuration.

**Comment by nicolodavis** [comment]
Thanks for the report! Do you want to send me a tiny fix for this? (I'll get to it eventually if you don't have the time).

**Comment by drsirmrpresidentfathercharles** [comment]
Sure! I'll get a pull request in soon.

**Comment by nicolodavis** [comment]
Thanks a lot!
