### ISSUE TITLE
Flow vs FlowWithPhases

### ISSUE THREAD

**Issue by iamchristopher** [google/boardgame.io#217]
According to comments left in the code, `FlowWithPhases` is intended to be a "very customizable game flow". However, in practice I've found myself quite hamstrung with it's implementation. Overall, `FlowWithPhases` has a larger number of options but `Flow` has some advanced options that aren't shared between the two (specifically, `ctx` and `canMakeMove`).

It's possible that I may be interpreting the system incorrectly, but how are we meant to do such things as define custom player order or validate a player move with `FlowWithPhases`?

**Comment by nicolodavis** [comment]
For flows, there are actually three possible ways you can go about customizing:

### 1. Write a raw flow all by yourself

This involves creating a flow reducer like this:

```
flow: {
  processGameEvent: (state, action) => {},
  ...
}
```

This is the return value of `Flow()` and allows you to do whatever you want basically. Most users will not want to do this.

### 2. Use Flow()

I don't recommend this either. `Flow()` is now more or less just an implementation detail of `FlowWithPhases()`. It started out as a simpler alternative, but I don't think that is the case any longer.

### 3. Use FlowWithPhases()

This is what most people should use. If there is some use-case that you have that should be solved by it (but isn't), we should just fix that.

Here are some tips on your more specific questions. Let me know if there is something missing, and we can discuss if it makes sense to improve `FlowWithPhases` to capture your use-case better.

##### Defining a custom turn order

This is documented [here](http://boardgame.io/#/turn-order).

```
flow: {
  turnOrder: {
    start: () => ...
    next: () => ...
  }
}
```

##### Validating player moves

If you want to disable certain types of moves in phases, you can use the `allowedMoves` [mechanism](https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L165).

If you want to disable a type of move with a specific combination of args, the best way to do this is to actually return `undefined` (or not return) in your move implementation. I've found that figuring out whether a move is valid or not often requires actually running the same code as executing the move itself, so this mechanism was introduced to make it convenient to invalidate moves in the same place the move is defined.

**Comment by nicolodavis** [comment]
(let's continue this discussion on Gitter rather than on the Issue Tracker)
