### ISSUE TITLE
can we update redux range to '3.7.2 - 4'?

### ISSUE THREAD

**Issue by amitport** [google/boardgame.io#238]
+ won't break users who explicitly depend on `^3.7.2`
+ seems to work OK for boardgame.io itself

**Comment by nicolodavis** [comment]
Done: https://github.com/google/boardgame.io/commit/14a5ad78105902352feaa341cd58983b9b474aed

**Comment by nicolodavis** [comment]
I wasn't looking to support 3.7.2 in particular (Redux is an internal implementation detail anyway).  Just updated it to 4.0.0.
