### ISSUE TITLE
How would be to have the example with two different players as two browser tabs?

### ISSUE THREAD

**Issue by saeidalidadi** [google/boardgame.io#24]

**Comment by nicolodavis** [comment]
You mean show each player controls / state that are relevant only to them?

Currently it's up to the game designer how they want to determine the "current player". The library doesn't have built-in support for a user account system (yet), so they have to decide how they want to map their notion of the logged in user to the current player.

Once they have this mapping, it's quite easy to make the board uninteractive while it's not the current player's turn, and activate it when it is. This is something that will be built in once we have a story for user authentication.

**Comment by saeidalidadi** [comment]
I mean just to have an example as a way that players after connecting to the server of current example so they could be as:
1. Host: number of connections  = odd
2. Guest: number of connections = even

so we can manage players on a demo server  
also we can add some features like `moving timeouts`  and persist data for test cases.

**Comment by nicolodavis** [comment]
We can actually show two different players on the same tab. https://github.com/google/boardgame.io/commit/959a9591ee12ee887c9380e23c2e6b43055207e4 implements this.

I think having a demo server always running is out of scope for the examples at the moment. Once we have some well implemented games, we can link to those and maybe have a demo server running.
