### ISSUE TITLE
Debug Panel - Overwrite PlayerID

### ISSUE THREAD

**Issue by RGBKnights** [google/boardgame.io#245]
When using the debug panel to overwrite the playerID by clicking on the player the game state and debug information is updated the board object is not. This could be a bug it could also be by design sometimes it hard to tell. 

The area in question is [here](https://github.com/google/boardgame.io/blob/268aab8b3c914cf88d62a188fd4f1ad4e854b7d5/src/client/react.js#L148). I believe this done so that the original props of the board are kept in tack regardless of the others. A good security measure, but when in debug mode it should be overwritable.

`
_board = React.createElement(board, {
 ...state,
isMultiplayer: multiplayer !== undefined,
moves: this.client.moves,
events: this.client.events,
gameID: this.gameID,
playerID: this.playerID,
reset: this.client.reset,
undo: this.client.undo,
redo: this.client.redo,
...rest,
});
`

The playerID is set as one of the options but it is overwritten by the value in `rest` which are the default properties of the board component in my case either NULL or default value from the board's properties. 

I think that the playerID should be removed from `rest` when Debug flag is set to True so the value set of the Debug panel translates to the Board component. This would make so that changing the player using debug effects the board.

IF there is a diferent way to do this that I do not understand please point me in that direction and close the issue.

**Comment by RGBKnights** [comment]
I now understand the issues with doing it this way and using the debug panel to overwrite these values...

**Comment by nicolodavis** [comment]
debug.js uses a callback that react.js uses to update its playerID.

Regardless of how it is implemented, just want to check if clicking on a player does in fact affect the board (my understanding is that it does, but your post seems to suggest otherwise). If not, that is a bug that we need to fix.

**Comment by RGBKnights** [comment]
Based on my setup and testing it did not update the params of the board correctly. I believe I indenify the section effecting this behaviour, details above.

If you can confrimed that section of code is indeed working correctly the I was indeed using it incorrectly and there is no issue. If indeed something looks fishy I can provide any details that help track down the issue.

**Comment by nicolodavis** [comment]
Do you have a minimal example that can reproduce the problem?

**Comment by RGBKnights** [comment]
Sure you have look that my prototype. I created a branch for this issue.
https://github.com/RGBKnights/Lusus/tree/RGB-TestForIssue245

You will need to start the server and client with npm run server and npm run client to get both pieces started. 

When up and running you can use the debug to try and change the player by clicking on the number you will see the debug info update but the board state will not change. 

https://github.com/RGBKnights/Lusus/blob/1b9a771bfef258d79cc0dc5c42a30003aac8381c/src/board.js#L101

Is the code that tests for the PlayerID on the board and makes the "Hand" visible to one player or the other. The PlayerID is always NULL even when I use the Debug panel to change the PlayerID.

After I applied the following patch to the React.js ln:2666 (in the node_modules folder) the board then updates correctly then I change the player using the Debug Panel.

`
if(debug) {
rest = objectWithoutProperties(rest, ['playerID']);
}
`

**Comment by nicolodavis** [comment]
Got it. Thanks for the report!

Fixed in 0.25.3.

**Comment by RGBKnights** [comment]
When upgrading I got the following issue (#250)[https://github.com/google/boardgame.io/issues/250]
