### ISSUE TITLE
Looking for mongodb and firebase despite not being configured to use

### ISSUE THREAD

**Issue by iamchristopher** [google/boardgame.io#249]
Looks like an issue may have been introduced with `v0.25.0` where the framework tries to access `mongodb` and `firebase` even if no persistent storage method is configured.

**Comment by iamchristopher** [comment]
Sorry, I should have provided more detail. I'm running a server in a multiplayer environment, all local. When I start said server the application throws with an error saying it can't find `mongodb` and `firebase`. If I manually install these dependencies everything works correctly.

Running `npm run dev` doesn't seem to repro this issue. My assumption is because these were marked as dev dependencies in the latest release and aren't included when installed in a project.

**Comment by nicolodavis** [comment]
Got it. I think these `require` statements should become conditional by going into the constructors of the Mongo and Firebase classes. My bad.

**Comment by iamchristopher** [comment]
All good! Thanks for all your hard work.

**Comment by nicolodavis** [comment]
Fixed in `0.25.1`.

**Comment by iamchristopher** [comment]
Tested and confirmed working. Thanks again!
