### ISSUE TITLE
ReferenceError: babelHelpers is not defined

### ISSUE THREAD

**Issue by RGBKnights** [google/boardgame.io#250]
When upgrading from 0.24.0 to 0.25.3 the application crashes with the following error:
`
ReferenceError: babelHelpers is not defined
(anonymous function)
~/Lusus/node_modules/boardgame.io/dist/react.js:2710
`

**Comment by Stefan-Hanke** [comment]
`babelHelpers` is defined in package `babel-plugin-external-helpers`. Can you add repro steps?

**Comment by RGBKnights** [comment]
I have tested this different ways now and each still result in the error. 

You can try upgrading [this](https://github.com/RGBKnights/Lusus/tree/RGB-TestForIssue245) branch from 0.24.0 to 0.25.3.

But I also got the same issue when I created a new project following the steps in the [tutorial](http://boardgame.io/#/tutorial) section of the documentation.

**Comment by nicolodavis** [comment]
I have a feeling package-lock got corrupted. Let me try publishing again later today.

**Comment by nicolodavis** [comment]
Should be fixed in 0.25.4. Can you check?

**Comment by RGBKnights** [comment]
Confirmed issue resolved
Thanks 👍
