### ISSUE TITLE
jest: sporadic "failed to cache transform results" error

### ISSUE THREAD

**Issue by Stefan-Hanke** [google/boardgame.io#254]
I'm observing sporadic errorneous behaviour when running tests.
janosimas reported the same issue here: #175 

![grafik](https://user-images.githubusercontent.com/1977938/43916051-cbfd1e30-9c0c-11e8-8427-7948ef70d1b0.png)

Observation: <s>For the last 4 occurrences, the error message is about file `random.alea.js`.</s>
Not true - sporadic on any test file.

**Comment by Stefan-Hanke** [comment]
The issue is already reported: https://github.com/facebook/jest/issues/4444
There is a sort-of fix to use a patched version of `graceful-fs`.

**Comment by Stefan-Hanke** [comment]
I've applied `patch-1` version of `graceful-fs` and it looks like it's working fine.

Would you mind a PR for this? We could leave this issue open to be reminded about jest behaviour, and eventually undo it should there ever be an official fix. Spoiler: It does not look like being fixed anytime soon, if ever.

Maybe I can apply that line at my machine locally only, so no source change is necessary. Is there a way to perform that, other than myself being really careful about `package.json` modifications?

**Comment by Stefan-Hanke** [comment]
I witness this error on a regular basis, in case of PR #252 , I had a streak of 4-5 times where that error occurred.

**Comment by nicolodavis** [comment]
Hmm, I just ran `npm install`on a clean version of the repo and I see:

```
+        "graceful-fs": {
+         "version": "4.1.11",
+          "resolved": "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz",
+          "integrity": "sha1-Dovf5NHduIVNZOBOp8AOKgJuVlg=",
+          "dev": true
+        },
```

in the diff of `package-lock.json` (under the dependencies section of `jest`).

I'm wondering if merely adding the patch to `graceful-fs` at the top level actually fixes it as a dependency for Jest, i.e. does Jest now use the patched version or does it continue to use the unpatched version?

**Comment by nicolodavis** [comment]
There is a separate question of should I commit this `package-lock.json` diff.  Ideally running an `npm install` on a clean repo should result in no diffs.

**Comment by Stefan-Hanke** [comment]
I don't know. Searching for _graceful-fs_ yields that all sorts of different versions are requested... (4.1.2, 4.1.4, 4.1.6, 4.1.11).

Looks like npm writes dependency information inside the package.json of the module itself, in case of _graceful-js_ it looks OK though:

`
"_resolved": "git+https://github.com/mekwall/node-graceful-js.git#a10aa576f771d7cf3dfaee523f2e02d6eb11a89f",`

, which is exactly [HEAD of the patch-1 branch](https://github.com/mekwall/node-graceful-fs/commit/a10aa576f771d7cf3dfaee523f2e02d6eb11a89f).

----
Unfortunately I continue to observe the error. Because of above I think npm resolved to the patch-1 version; if so, I'll just have to accept jest behaviour.

**Comment by Stefan-Hanke** [comment]
So I performed a fresch clone, run `npm i`, and there are a lot of diffs inside file package.lock. I'm not sure but looks like this is dependend on the npm version? I'm on npm version 6.4.0, node version 10.5.0.

Unfortunately the package.lock now looks a bit different, there is no mention of the patch-1 branch anymore, but only to the commit hash (albeit the right one).

**Comment by ksjogo** [comment]
Is this still needed? Having this as dependency breaks things with pnpm.

**Comment by nicolodavis** [comment]
Perhaps it is indeed time to evaluate if this can be removed.  Thanks for looking into this @ksjogo!
