### ISSUE TITLE
Game Logic Test Example

### ISSUE THREAD

**Issue by yairhaimo** [google/boardgame.io#260]
It would be great to have an example on how to test the game logic itself without the UI layer and without using low level (redux) methods such as creating a reducer and dispatching events.

**Comment by nicolodavis** [comment]
The game logic itself should consist of pure functions, so you can test those functions directly.

```js
// Test these as individual functions.
function MoveA(G, ctx) { ... }
function MoveB(G, ctx) { ... }

Game({
  moves: { MoveA, MoveB }
})
```

You don't have to inline the move functions in the Game config.

**Comment by yairhaimo** [comment]
Could this be a valid test?
```
import {  TicTacToe } from './App';
import { Client } from 'boardgame.io/client';

it('should work', () => {
  const client = Client({
    game: TicTacToe
  });
  client.moves.clickCell(1);
  client.events.endTurn();
  client.moves.clickCell(2);
  const { G } = client.store.getState();
  expect(G.cells).toEqual([null, '0', '1', null, null, null, null, null, null]);
});
```

**Comment by yairhaimo** [comment]
But maybe you want to test scenarios and not just unit test the functions. 
Scenarios such as a full game of tic tac toe which tests that each player has only one turn, the output of each move, winning and tie scenarios.

**Comment by nicolodavis** [comment]
Yeah, that's true.  In that case what you suggested looks fine.

I'll close this issue if it resolves your question (feel free to continue discussion of course, or reach out on [Gitter](https://gitter.im/boardgame-io/General)).
