### ISSUE TITLE
clientInfo.get returns undefined for connected client in authenticated example

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#264]
This line [here](https://github.com/google/boardgame.io/blob/master/src/server/transport/socketio.js#L27) should not return `undefined`.

Steps to reproduce:
- Go to the authenticated example
- Hit browser refresh
- The server will display an error that says: "Cannot read property 'playerID' of undefined"

**Comment by Stefan-Hanke** [comment]
After spending ~2h on this I need to brush up on my debugging skills. I currently resort to good-old `printf` debugging. This is complicated by the fact that `JSON.stringify` does not work on Maps/Sets directly, so I used `flatted`. However this is no plain JSON output anymore.

All that I got is that `roomInfo` still contains invalid/old socket ids, even after disconnect has deleted them. Don't know why this is happening.

**Comment by nicolodavis** [comment]
Thanks for digging into this @Stefan-Hanke. Yeah, I noticed the stale socket ID's in `roomInfo` as well. I'm not sure why that's happening either.

Given that this only happens for the authenticated example, I'm inclined to believe that it's either something that has to do with the way it creates / joins games as opposed to a socket.io quirk that we're not accounting for. Hopefully I'll get some time later this week to dig further.

**Comment by nicolodavis** [comment]
The problem is that the authenticated example joins a game `tic-tac-toe:gameID` first, then creates a game through the game creation API and joins that after. The sockets in the meantime just move from one game to the next (there is no disconnect). This causes `roomInfo` to contain entries for the sockets in both games (and, `clientInfo` points to the new game, so we've effectively lost the pointer to the old game instance).

When you hit refresh, the example again joins `tic-tac-toe:gameID` (this time with new sockets). So, `roomInfo` now contains four entires (two new sockets and two old). The old sockets don't have entries in `clientInfo` anymore, which causes the error.

The fix is easy: https://github.com/google/boardgame.io/commit/5d6e23d3f56a1fd9ebdc8278e22ef34aae43e36f
