### ISSUE TITLE
Utilities for simplifying working with hexagonal boards

### ISSUE THREAD

**Issue by Korla** [google/boardgame.io#266]
@nicolodavis suggested that we implement a couple utility functions to make it easier to work with the hexagonal boards. I've been looking at ["the blog"](https://www.redblobgames.com/grids/hexagons/) for guidance on how to handle some simple calculations already, and when looking it over again I figured that the following would be a good start:

- Getting all neighbors for a point
- Calculating distance between points

We could also extend this to getting points on a line between two points, all neighbors within a specific distance, intersections between ranges, etc.

On a branch I have started implementing this as a set of exported functions in a file called hexUtils which has a single export which is also exported in `packages/ui.js`. Another approach is to implement these functions as static methods on the `HexGrid` class.

Let me know if this is something I should make a PR for, and if you have any ideas how this should be implemented.

**Comment by Korla** [comment]
Alright, I'll get a PR up soon. Should this be documented as well?

**Comment by nicolodavis** [comment]
No need to document it. I'll document it later once the UI framework is a bit more stable.
