### ISSUE TITLE
Integrating with other Game Engines

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#272]
I'm not sure how many people are currently using libraries like Phaser, BabylonJS or threejs with a vanilla boardgame.io client.

However, just picturing what that workflow might look like, I'm wondering if there are some difficulties that we could address. For example, at the end of each move, we currently export the new game state. For a React client, you basically provide a declarative description of how to translate that game state into UI elements, and React takes care of doing that efficiently.

I'm not sure how to do this easily in something like threejs, though. You don't want to clear and recreate your entire scene after each move. Rather, you want to move just that one token that was changed during the latest move (and possibly animate it). This is possible by keeping additional rendering state and doing the diffing yourself, but I'm wondering if we can make it even easier.

For example, what if we provide a mechanism to not merely export new state, but also a description of what "moved" on the board (this would be completely optional, and analogous to our game log). This is a generic representation of the UI that is then translated to your game engine's primitives.

In general I'm starting to think that a generic UI representation (using primitives that we define like "token", "card", "hex tile" etc.) would constitute a proper UI framework offering (as opposed to a mere component set in React in #48). The advantage here is that we could write adapters for various frameworks that could automatically translate our UI representation to rendered games in those respective frameworks (and you have one codebase that can be magically rendered to React or threejs without having knowledge of either framework). People are still free to consume the raw state or consume the UI representation (but not use our auto-rendering) if they want tighter control.

**Comment by nicolodavis** [comment]
@iamchristopher I remember you mentioning that you're using Phaser?

**Comment by iamchristopher** [comment]
@nicolodavis Yes, I'm using Phaser. I'm not sure how much rendering we could do automatically, but we could create a plugin that handles connecting to the server and emitting client-side events. I'll give it some thought.

**Comment by nicolodavis** [comment]
I'm more interested in the handling of deltas actually. How do you currently rerender your game scene when the game state changes?

**Comment by iamchristopher** [comment]
Very crudely. I have a few system components that subscribe to the store and translate changes to game events (ie, pawn movement).

**Comment by nicolodavis** [comment]
I guess the question is how do you "translate changes"?

Do you look at every object in the state and then move all pawns to their locations as specified in the state? Or do you have some sense of what needs to move and only update those pawns?

**Comment by iamchristopher** [comment]
A pawn checks against its position before moving based on a sync event. Unfortunately there isn't currently a way to only compare against a diff caused by the most recent action.

**Comment by nicolodavis** [comment]
In theory you can store that diff yourself inside `G` (compute the diff inside your move and write it to `G.diff`). It tightly couples your game state and rendering state, but that's one way.

Maybe that's the best approach from the point of view of the framework (i.e. do nothing and leave it up to the developer to compute these incremental diffs I needed). About auto rendering, that's a separate topic and I'll create a separate issue for that once I've played around with the idea and come up with a viable proposal.

I'll close this issue then. Lets continue this discussion on Gitter.
