### ISSUE TITLE
npm package problem - node v6.10.1

### ISSUE THREAD

**Issue by ahmetoz** [google/boardgame.io#30]
I'm not sure if this is an error but npm package does not works on node v6.10.1. (windows 10)

And thank you for this awesome framework. 👍 

```
11986 error Windows_NT 10.0.15063
11987 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "boardgame.io"
11988 error node v6.10.1
11989 error npm  v3.10.10
11990 error code ELIFECYCLE
11991 error boardgame.io@0.11.4 postinstall: `ln -s ../packages/node_modules/boardgame.io`
11991 error Exit status 1
11992 error Failed at the boardgame.io@0.11.4 postinstall script 'ln -s ../packages/node_modules/boardgame.io'.
11992 error Make sure you have the latest version of node.js and npm installed.
11992 error If you do, this is most likely a problem with the boardgame.io package,
11992 error not with npm itself.
11992 error Tell the author that this fails on your system:
11992 error     ln -s ../packages/node_modules/boardgame.io
11992 error You can get information on how to open an issue for this project with:
11992 error     npm bugs boardgame.io
11992 error Or if that isn't available, you can get their info via:
11992 error     npm owner ls boardgame.io
11992 error There is likely additional logging output above.
11993 verbose exit [ 1, true ]
```

**Comment by ChargerIIC** [comment]
I seem to be receiving the same error. I got this on Windows 10, executed via PowerShell on NPM 5.6.0:

> boardgame.io@0.11.4 postinstall C:\users\vburt\documents\github\boardgame\node_modules\boardgame.io
> ln -s ../packages/node_modules/boardgame.io

'ln' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boardgame.io@0.11.4 postinstall: `ln -s ../packages/node_modules/boardgame.io`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the boardgame.io@0.11.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vburt\AppData\Roaming\npm-cache\_logs\2017-12-19T21_45_40_560Z-debug.log

Is 'ln' a batch command that is OS specific? Is there another package that is required for the install to work?

**Comment by nicolodavis** [comment]
This should be fixed by #13

**Comment by kaffeskogen** [comment]
I just pulled the latest version and got a similar result as @ChargerIIC.

`'ln' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boardgame.io@0.11.4 postinstall: \`ln -s $PWD/packages/ $PWD/node_modules/boardgame.io\`
npm ERR! Exit status 1`

NPM 5.6.0
Node 8.5.0
Windows 10

**Comment by dm67x** [comment]
I have the same problem with npm and yarn. It's a problem with symbolic link, by the way i'm on Ubuntu 16.04 64 bits.

![capture du 2017-12-23 18-51-13](https://user-images.githubusercontent.com/1593334/34321568-744237a6-e812-11e7-8238-8c1053024114.png)

**Comment by nicolodavis** [comment]
The symlinking seems quite brittle. Will think of a different way to do it that doesn't involve this hack.

**Comment by nicolodavis** [comment]
For context, the reason the symlink exists is so that the example code can do

```
import Game from 'boardgame.io/game'
```

and it imports code from the repo instead of the version on npm (useful for developers to make changes to the library and see it reflected in the example right away).

**Comment by saeidalidadi** [comment]
The best practice for linking local packages is the private package option as below:
1. Move each file inside a new directory.
2. Add `package.json` with these options.
```
{
  "private": true,
  "name": "pachageName",
  "version": "0.0.0"
}
```
3. Run `npm link` form packages.
4. Run `npm link packageName` for each package.

**Comment by rlesniak** [comment]
Same problem here! Cant install 

`npm ERR! boardgame.io@0.13.0 postinstall: ln -s $PWD/packages/ $PWD/node_modules/boardgame.io`

Node: 9.3.0
macOS: 10.13.1

**Comment by dm67x** [comment]
I have the problem with symlink but the lib working without problem. I have all the files inside my node_modules directory.
![capture du 2017-12-23 23-47-04](https://user-images.githubusercontent.com/1593334/34323148-06485436-e83c-11e7-9a53-8e37fc7974da.png)

I test it with the tutorial code and it seems to work well.
![capture du 2017-12-23 23-48-58](https://user-images.githubusercontent.com/1593334/34323150-0b9055b0-e83c-11e7-82cb-e83d4b87ae5c.png)

**Comment by vntrungld** [comment]
I use node v8.9.3 and have this problem too.

**Comment by nicolodavis** [comment]
I think this should now be resolved.

Can someone that had this problem before verify?

**Comment by vntrungld** [comment]
Oh! I tried to remove node_modules and `yarn` again, then `yarn add boardgame.io` with no problem

**Comment by rlesniak** [comment]
@nicolodavis I had and I can verify that 0.13.1 resolves this issue. Thanks! :)

**Comment by nicolodavis** [comment]
Great!
