### ISSUE TITLE
Q: can this be used to implement a game like bughouse

### ISSUE THREAD

**Issue by mallochine** [google/boardgame.io#32]
Just a question. EOM.

**Comment by nicolodavis** [comment]
Are turns in bughouse made in a certain order?

**Comment by mallochine** [comment]
bughouse is two-board chess, 4-player game.

**Comment by saeidalidadi** [comment]
@mallochine Yes, if the game is a turn based. it means that while one is playing others are waiting.

**Comment by nicolodavis** [comment]
The current turn model is a round-robin, which works for many games, but not all. If players in bughouse can take a turn "whenever they are ready", and not following a particular order, the current library as it stands will not support this use-case well.

We have plans to make the turn model extensible, so game authors can plug their own logic to how the turn passes between players, so games that require unnatural orders can also be supported.

**Comment by mallochine** [comment]
well it's like 2 parallel games of chess.

**Comment by nicolodavis** [comment]
FYI, you can implement this pretty easily after v0.16.

**Comment by mallochine** [comment]
can you quickly tell me how? Anything I can read?

**Comment by nicolodavis** [comment]
http://boardgame.io/#/phases should have everything you want to know. Feel free to ask here too if you have any questions.
