### ISSUE TITLE
socket isolation

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#41]
The current multiplayer code only works fine for a single 2-player game. Small improvements necessary to scale to more players and games:

* **More socket metadata** - The multiplayer code must stop broadcasting state updates, but send individual updates to various connected sockets that must advertise whether they belong to a particular player.

* **Rooms / namespaces** - State updates for a particular game must only go to clients connected to that particular game.

**Comment by saeidalidadi** [comment]
Small improvements based on this consideration that games could be on multiple instances or services(stateless server)
