### ISSUE TITLE
localStorages in multiplayer mode are in complete sync. How do I save different identity info?

### ISSUE THREAD

**Issue by FateRiddle** [google/boardgame.io#46]
I try to make the demo tic-tac-toe truly multiplayer, that is, you can only clickCell on your turn.
So I tried to save `playerId` in `localStorage`, only when `currentPlayer` equals `playerId` can you make a move.
But then I find the `localStorage` in different open tabs are in complete sync. So I wander what do I do, when I need localStorage to save unique information in different tabs.

BTW, node.js has no localStorage, but likely localStorage is part of game rules information, so does it matter if I pass a null function as localStorage into backend code?

**Comment by nicolodavis** [comment]
https://github.com/google/boardgame.io/commit/959a9591ee12ee887c9380e23c2e6b43055207e4 implements this. Take a look, and feel free to re-open this if you think we should do more.
