### ISSUE TITLE
Proper way to sort out the next `currentPlayer` when turn ended?

### ISSUE THREAD

**Issue by lionng429** [google/boardgame.io#50]
the current player should be a function of `ctx` and `game` so it opens up the flexibility to sort out the next current player for different game.

For example:
UNO: reverse card, skip card
Poker: cards have been folded

```
const getCurrentPlayer = (ctx, game) => {
  let nextPlayerIndex = (+ctx.currentPlayer + 1) % ctx.numPlayers + "";

  while (nextPlayerIndex !== ctx.currentPlayer) {
    const { status } = game.players[nextPlayerIndex];

    // to check next player state
    // it implies all related player state changes should be done
    // in the previous action move
    if (!status.skipped && !status.banned && !status.folded) {
      return nextPlayerIndex;
    }

    nextPlayerIndex = (+nextPlayerIndex + 1) % ctx.numPlayers + "";
  }

  return nextPlayerIndex;
};
```

```
// src/core/reduce.js
export function createGameReducer({game, numPlayers, getCurrentPlayer}) {
...
...
    // Update current player.
    const currentPlayer = getCurrentPlayer ? getCurrentPlayer(ctx, game) :
      (+ctx.currentPlayer + 1) % ctx.numPlayers + "";
...
...
```

This is the brief idea about the `getCurrentPlayer` function.

It will be even better to integrate with [reselect](https://github.com/reactjs/reselect) that allows to provide getters/selectors from store.

Any feedback is welcome! Thank you for your time to read through.

**Comment by nicolodavis** [comment]
Hey @lionng429. I've actually been working on a generalized version of just this: A way to define "phases" in the game, and some hooks to customize how the turn gets passed around between the players and also the board (you might want some actions that the board executes).

Happy to get just this bit in if you want to send me a Pull Request. If not, this use-case should be taken care of once I finish up work on "phases".

**Comment by nicolodavis** [comment]
duplicate #51

**Comment by nicolodavis** [comment]
In case you are interested in following progress on this, take a look at the [phases](https://github.com/google/boardgame.io/commits/phases) branch.

**Comment by lionng429** [comment]
thanks @nicolodavis, I will take a look at that.
