### ISSUE TITLE
Solitaire game with others watching over websockets?

### ISSUE THREAD

**Issue by anton-107** [google/boardgame.io#57]
Hi, I'm designing a board game for single-player.

I was wondering if it's possible with boardgame.io to create a proper game with number of players to equal 1? (right now I'm automatically skipping a turn of other players)

I'm also interested if I can use boardgame.io 's multiplayer mechanism for other players to join watching the solitaire game in real-time?

**Comment by nicolodavis** [comment]
Yes, just set `numPlayers` to 1 and it should work. To have others spectate, use `multiplayer: true` when creating the client, set `playedID = "0"` on the client that is actually playing, and have other clients connect without a `playerID`.

There is an example to do just this in the repository. Have a look!

**Comment by gk-patel** [comment]
Are you sure that spectoator view is still allowed, considering, 

https://github.com/nicolodavis/boardgame.io/blob/master/src/server/api.ts#L163

**Comment by delucis** [comment]
@gk-patel The `/join` endpoint is only for active players when they first join a game. Spectators should use the `/games/:name/:id` endpoint ([source](https://github.com/nicolodavis/boardgame.io/blob/5c9430f0f482f23d98e9aa5636125ae67fd48bb0/src/server/api.ts#L143)).
