### ISSUE TITLE
Grid system with (Hex) tile

### ISSUE THREAD

**Issue by lionng429** [google/boardgame.io#58]
Has anyone started working on the grid system yet? Mind if I give a go?

I am going to make a GridSystem component handling dimensions, coordinations and drag and drop, and also a dump HexTile component.

I haven't started yet so please feel free to let me know if anyone started working on this.

Cheers.

**Comment by nicolodavis** [comment]
Get in on the conversation at #48. Looking forward to your contribution!

**Comment by nicolodavis** [comment]
Closing this as a duplicate of #48
