### ISSUE TITLE
Multiple actions in handler not receiving updated state

### ISSUE THREAD

**Issue by michaelmior** [google/boardgame.io#63]
I have a click handler that conditionally executes multiple game moves since several may be triggered by a player action. However, I see that the component props are not updated until after my callback returns even though the game state is changed. Any way to work around this?

**Comment by nicolodavis** [comment]
When you say the game state is changed, you mean you are able to see the new state on the Debug UI? Which props do you find are stale? What is this callback you are referring to (did you mean click handler)?

**Comment by michaelmior** [comment]
Yes, I meant click handler. Specifically, the game state is stale. For example, I have an action called `selectDie` and in that action, I log the new state produced. Immediately after calling that action, I see the state has correctly changed, but `this.props.G` still refers to the old state.

**Comment by nicolodavis** [comment]
Do you have a link to your code? I can take a look and see what's going on.

**Comment by michaelmior** [comment]
Thanks! Unfortunately, the code is a bit of a mess now since I just started working on the project this afternoon. Here is [the line](https://github.com/michaelmior/lasvegas-web/blob/822e6321116c00a43d8d5fc14e1d91db80a38c6e/src/App.js#L126) where I specifically call my move. The logging statement after shows that the game state is stale.

**Comment by nicolodavis** [comment]
https://github.com/reactjs/react-redux/issues/748 should answer your question.

Also, I would recommend keeping clickHandlers fairly simple. There shouldn't be much game logic in there. Your game might also benefit from the upcoming support for [phases](https://github.com/google/boardgame.io/issues/51).

**Comment by michaelmior** [comment]
@nicolodavis Yes, I agree that the handler is getting too complex. I've been watching the phases support and I think that would likely make things much cleaner. Is it currently possible to call a move (or `endTurn`) from within another move?

**Comment by nicolodavis** [comment]
Calling an action from a reducer (move handler) is generally considered an anti-pattern.

I think the phases support should help with this. There are hooks to automatically end a phase when a particular condition is met.

I'll add something similar for ending turns.

**Comment by michaelmior** [comment]
Thanks! This is just a fun side project so I'll probably just wait until phases support lands.
