### ISSUE TITLE
Automatic Secret State

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#72]
Would be nice to have some conventions that tell the framework to automatically strip out data from `G` before sending data to a particular client. The current mechanism involves having to implement `playerView` as documented [here](http://boardgame.io/#/secret-state).

We could bundle in an (opt-in) implementation of `playerView` that does the following:
- Drop fields with a key `secret`.
- When there exists an object called `players`, drop all the keys from it that aren't `playerID` (i.e. each player only receives their slice of that object).

```
players: {
  '0': ...
  '1': ...
  '2': ...
}

becomes

players: {
  '1': ...
}

for player 1.
```

**Comment by philihp** [comment]
Sounds like a positive change to me!

Perhaps the default playerView could call a reducer that does this, but can be overridden, similar to how TurnOrder’s default cycles through?

**Comment by nicolodavis** [comment]
Opt-in vs opt-out is always a tricky question. In the case of a turn-order, you always want it to do *something*, which is why a default makes sense. In this particular case, there might be some users that will be surprised that their field named `secret` vanished without them doing anything, so I would err more on the side of having the user needing to explicitly enable this behavior.

**Comment by arakholia** [comment]
For say cards in a player's hand where the _existence_ of the item is a public state and the _content_ is private, would the idea be the existence of the card is elsewhere in G and the players[id] contains the actual content? An alternative implementation may be having the owner specified in each card/token/object, and playerView filters each object depending on whether the ownerID matches the client player ID. Although this would mean playerView would have to traverse the entire tree when sending G to each player to determine what to filter. This does certainly sound silly, even though it may be more natural?

**Comment by philihp** [comment]
@arakholia Could you give an example game state that that would look like?

My feeling is that usually the hidden information a player has privy to is usually small compared to the rest of the information on the table; like in Settlers the resources you have in hand is small compared to the state of the island's cities and roads.

So then a convention of keeping hidden stuff inside of `players` would work well in this situation.

```js
let StripSecrets = (G, playerID) => ({
  ...G,
  players: {
    [playerID]: G.players[playerID]
  }
})
```

The only counter-example I can think, where stuff "on the table" is public would be a game like Stratego or Guess Who, where a person's physical perspective lets them see things that opponents can't.

**Comment by nicolodavis** [comment]
@arakholia In the case of cards, the best option might be to implement `playerView` yourself in order to transform:

```
cards: [ { type: 'cardA' }, { type: 'cardB' } ]
```

to

```
cards: [ { type: 'unknown' }, { type: 'unknown' } ]
```
