### ISSUE TITLE
node-sass?

### ISSUE THREAD

**Issue by chrisheninger** [google/boardgame.io#78]
Noticed node-sass in the package.json file– yet I don't think we're using sass anywhere?

It's a pretty gnarly install– would be nice to chop it out (along with any other unused dependencies).

**Comment by nicolodavis** [comment]
I think I initially envisioned using SCSS for the CSS files and then had trouble figuring out how to use it with Rollup. I'm going to refactor debug.css to use some nested rules. I'll remove this dependency until that happens.

**Comment by nicolodavis** [comment]
Fixed by https://github.com/google/boardgame.io/commit/031ad291d245325d11be744a3acb3abf83e3c4ba
