### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by Jonovono** [google/boardgame.io#8]
This looks awesome! Has this been used in React native?

**Comment by nicolodavis** [comment]
React Native is outside scope at the moment until Facebook re-licenses it under MIT like they did for React here: https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

In the meantime, feel free to create a separate repo for React Native support. Happy to provide advice. The hope is that we'll have many different client implementations (React, Vue, React Native etc.) in the future.

**Comment by saintplay** [comment]
So, is this tightly coupled to React?
Can I get started with Vue right now?

**Comment by nicolodavis** [comment]
It's not really tightly coupled to React (but all the provided components will be for React).

It should be possible (with some modifications) to make it work with Vue.

**Comment by nicolodavis** [comment]
[This](https://github.com/google/boardgame.io/blob/master/src/client/client.js) is the only React specific logic on the client-side.

It wraps the Redux store and some event generators in a React component. Should be fairly easy to make one for Vue as well.

**Comment by saintplay** [comment]
Sure, I would like to give it a try for one of my Vue projects! What would be a proper way to request some assistant?

**Comment by nicolodavis** [comment]
You mean get some contributors?

You can fork this project, make some modifications to have something working, and then maybe post on the Issue Tracker here to see if people want to contribute.

**Comment by virtuoushub** [comment]
FWIW, react native is now under the MIT license. https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88

**Comment by chrisheninger** [comment]
@virtuoushub I chatted with Nicolo last night– it's in the works under https://github.com/google/boardgame.io/issues/96 👍
