### ISSUE TITLE
Last turn not captured in log

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#80]
Suggestions:
- Also end the turn when `endGameIf` returns true.
OR
- Make `GameLog` add an entry on `gameover` in addition to the turn end.

**Comment by Stefan-Hanke** [comment]
Hi Nicolo,
I'm using this issue to get into the code base over this weekend.

For the TicTacToe example, the log already contains the last MAKE_MOVE action. I'd try going with your first suggestion and not have a gameover event currently.

I'm not sure my reasoning for this is correct; there are games that end immediately, or end after the current players turn, or allow subsequent players to make one last turn.

**Comment by Felizardo** [comment]
@Stefan-Hanke I just saw your comment now after sending the PR, otherwise I would have let you do it ! Sorry :(

**Comment by nicolodavis** [comment]
@Stefan-Hanke Is there anything else you'd like to take a look at? I can certainly help you find something bite-sized to get started if you're interested.

**Comment by Stefan-Hanke** [comment]
@Felizardo No problem. This gives me the opportunity to read your proposed changes and learn from it.

@nicolodavis  For now I'm falling back to just reading the source, please just keep having issues labeled with _good first issue_. I'll grab one in the next days.
