### ISSUE TITLE
Add option in Client config to specify socket server

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#85]
Currently you can only wire it to the same server that serves up the webpage.

An option like:
```
Client({
   game: TicTacToe,
   multiplayer: { server: 'hostname:port' },
})
```

would allow serving the page and game logic from different servers. Might also help the `create-react-app` users.

**Comment by chrisheninger** [comment]
👏 Setting this up in my game now, thank you for adding it! 🙂
