### ISSUE TITLE
Tic-tac-toe demo counts subsequent clicks on filled cells as turns

### ISSUE THREAD

**Issue by xhroot** [google/boardgame.io#9]
It appears that either player's turn is skipped if they click on a filled cell.  Debug sidebar shows `turn` increments.  Looks like this is checked in https://github.com/google/boardgame.io/blob/master/examples/tic-tac-toe/tic-tac-toe.js#L81 so I'm not sure what's up.

Repro:
* Go to https://google.github.io/boardgame.io/react/example-2.html
* click cell 0
* click cell 0
* click cell 1
* click cell 1
* click cell 2
* click cell 2

Result:
* 0-0-0 in top row

Expected:
* 0-1-0 in top row

**Comment by leeallen337** [comment]
I think I have a fix for this issue in this pull request: https://github.com/google/boardgame.io/pull/12
