### ISSUE TITLE
Prevent endTurn until movesPerTurn is satisfied

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#91]
There is a mechanism to end the turn automatically after a number of moves have been made: https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L83

We'd like to extend this so that the turn cannot be ended earlier (via `endTurn`) until these many moves have indeed been made.

**Comment by akaguny** [comment]
You whant to add any conditional to https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L131?
any :
```javascript
let acceptToEndTurn,
     G;
acceptToEndTurn = movesPerTurn && ctx.currentPlayerMoves >= movesPerTurn;
if(acceptToEndTurn !== false){
  G  = onTurnEnd(state.G, state.ctx);
}
```

**Comment by karel1980** [comment]
A practical solution is to just disable endTurn calls, and implement endTurn as a move, which sets a flag on the game state. The flag would be picked up by endTurnIf

**Comment by nicolodavis** [comment]
@akaguny Yes, something similar to that.

@karel1980 Disabling state changing signals like `endTurn` and `endPhase` is a good idea too. Perhaps we could have an option like `allowedSignals` (similar to `allowedMoves`) to specify which in `endTurn` and `endPhase` is allowed.

No reason not to have both! Would you guys be interested in sending me PR's for your respective suggestions? I'll eventually get down to them if you haven't got the time.

**Comment by akaguny** [comment]
@nicolodavis i want to make PR if @karel1980 don't worry for this, because it`s him bug)

**Comment by karel1980** [comment]
@nicolodavis you argument makes sense. I don't mind sending a PR either.

**Comment by karel1980** [comment]
@nicolodavis @akaguny Please see comments on the PR, there's still a few concerns, but it's a step in the right direction I think.

**Comment by akaguny** [comment]
@nicolodavis, i think that idea about allowedSignals not good because programmist must think and prevent manual execution of the endturn signals by heself, and if endTurn can be execute by player he must disable this feature in interface

**Comment by nicolodavis** [comment]
@akaguny I disagree. I personally think that users will find it surprising that they need to enable a feature like ending a turn before being able to use it (and will probably trip a lot of people learning the library). It feels more like a feature for an advanced user, so I'm leaning toward making it opt-out (i.e. all events are enabled by default, and we provide a mechanism to disable them).

**Comment by akaguny** [comment]
@nicolodavis yes, i'm also think that all the feature enable by default it's true way. I'm talked about another) But my english is no good and i may take some issues described my meaning about this

**Comment by nicolodavis** [comment]
Both proposals have now been implemented, so closing this.
