### ISSUE TITLE
Decouple client from React

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#96]
Current plan:
- Extract all the code in `client.js` into a JS object that can be used by itself from any view library.
- Provide a `react-redux` style connector from this object to props so it can be used in React just like today with minimal to no change to the API.

**Comment by nicolodavis** [comment]
This is now implemented! Happy to review PR's for anyone that wants to add React Native or Vue.

**Comment by bmayen** [comment]
Or Angular? :)
